import Head from 'next/head'

import Title from './components/Title'
import Searchbar from './components/Searchbar'
import Filter from './components/Filter'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Foo Scraper</title>
        <meta name="description" content="Generated by Sophia" />
        <link rel="icon" href="/favicon.ico" />
        <script src="../path/to/flowbite/dist/flowbite.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.1/dist/flowbite.min.css" />
        <script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script> 
      </Head>


      <Title/>
      <Searchbar/>
      <Filter/>
    
        
        

        
     



    </div>
  )
}
